version: "3.1"
services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
  
  integration-test:
    image: imixs/imixs-integration-test:4.5.6
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/workflow-db"
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    
    
    
#  imixsadmin:
#    image: imixs/imixs-admin
#    ports:
#      - "8888:8080"